import { Router } from "express";
import { adminRoutes } from "../modules/admin/admin.routes";
import { aiRoutes } from "../modules/ai/ai.routes";
import { analyticsRoutes } from "../modules/analytics/analytics.routes";
import { authRoutes } from "../modules/auth/auth.routes";
import { cartRoutes } from "../modules/cart/cart.routes";
import { catalogRoutes } from "../modules/catalog/catalog.routes";
import { checkoutRoutes } from "../modules/checkout/checkout.routes";
import { financeRoutes } from "../modules/finance/finance.routes";
import { healthRoutes } from "../modules/health/health.routes";
import { marketingRoutes } from "../modules/marketing/marketing.routes";
import { messagingRoutes } from "../modules/messaging/messaging.routes";
import { merchantRoutes } from "../modules/merchant/merchant.routes";
import { notificationModuleRoutes } from "../modules/notification/notification.routes";
import { orderRoutes } from "../modules/order/order.routes";
import { paymentRoutes } from "../modules/payment/payment.routes";
import { profileRoutes } from "../modules/profile/profile.routes";
import { reviewRoutes } from "../modules/review/review.routes";
import { riderRoutes } from "../modules/rider/rider.routes";
import { searchRoutes } from "../modules/search/search.routes";
import { securityRoutes } from "../modules/security/security.routes";
import { storeRoutes } from "../modules/merchant/store.routes";
import { systemRoutes } from "../modules/system/system.routes";
import { trackingRoutes } from "../modules/tracking/tracking.routes";

export const apiRoutes = Router();

apiRoutes.use(healthRoutes);
apiRoutes.use(systemRoutes);
apiRoutes.use(authRoutes);
apiRoutes.use(profileRoutes);
apiRoutes.use(merchantRoutes);
apiRoutes.use(storeRoutes);
apiRoutes.use(catalogRoutes);
apiRoutes.use(searchRoutes);
apiRoutes.use(cartRoutes);
apiRoutes.use(checkoutRoutes);
apiRoutes.use(paymentRoutes);
apiRoutes.use(orderRoutes);
apiRoutes.use(riderRoutes);
apiRoutes.use(trackingRoutes);
apiRoutes.use(messagingRoutes);
apiRoutes.use(notificationModuleRoutes);
apiRoutes.use(reviewRoutes);
apiRoutes.use(financeRoutes);
apiRoutes.use(analyticsRoutes);
apiRoutes.use(adminRoutes);
apiRoutes.use(marketingRoutes);
apiRoutes.use(securityRoutes);
apiRoutes.use(aiRoutes);
